export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_TOTAL_COST = 'UPDATE_TOTAL_COST';
export const UPDATE_LOADED_ITEMS = 'UPDATE_LOADED_ITEMS';
export const SEARCH_ITEMS = 'SEARCH_ITEMS';
export const UPDATE_SORTING_METHOD = 'UPDATE_SORTING_METHOD';
export const UPDATE_FILTER_METHOD = 'UPDATE_FILTER_METHOD';
